//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sehir_İlce_Mahalle_Web_Servis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public byte ID { get; set; }
        public string TEXT { get; set; }
    }
}
