//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sehir_İlce_Mahalle_Web_Servis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class developer
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string MAIL { get; set; }
        public string PHONE { get; set; }
        public string WEBSITE { get; set; }
    }
}
