//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sehir_İlce_Mahalle_Web_Servis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TurkeyLocationEntities : DbContext
    {
        public TurkeyLocationEntities()
            : base("name=TurkeyLocationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<datum> data { get; set; }
        public virtual DbSet<developer> developers { get; set; }
    
        [DbFunction("TurkeyLocationEntities", "ShowDistrict")]
        public virtual IQueryable<ShowDistrict_Result> ShowDistrict(string city)
        {
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ShowDistrict_Result>("[TurkeyLocationEntities].[ShowDistrict](@city)", cityParameter);
        }
    
        [DbFunction("TurkeyLocationEntities", "ShowTown")]
        public virtual IQueryable<ShowTown_Result> ShowTown(string city, string district)
        {
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var districtParameter = district != null ?
                new ObjectParameter("district", district) :
                new ObjectParameter("district", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ShowTown_Result>("[TurkeyLocationEntities].[ShowTown](@city, @district)", cityParameter, districtParameter);
        }
    }
}
